package com.diamante.orderingsystem.integration.order;

import com.diamante.orderingsystem.OrderingSystemApplication;
import com.diamante.orderingsystem.TestDatabaseSetup;
import com.diamante.orderingsystem.entity.*;
import com.diamante.orderingsystem.service.customer.CustomerService;
import com.diamante.orderingsystem.service.order.OrderService;
import com.diamante.orderingsystem.service.product.ProductService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataRetrievalFailureException;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import javax.transaction.Transactional;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import static com.diamante.orderingsystem.entity.Category.HOME_LIVING;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = OrderingSystemApplication.class)
@Transactional
public class OrderControllerIntegrationTest extends TestDatabaseSetup {

    @Autowired
    WebApplicationContext webApplicationContext;

    @Autowired
    CustomerService customerService;

    @Autowired
    ProductService productService;

    @Autowired
    OrderService orderService;

    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper mapper;

    // region test variables
    private Order order1;
    private Order order2;
    private Order order3;

    private Product product1;
    private Product product2;
    private Product product3;
    private Product product4;
    private Product product5;
    private Product product6;
    private Product product7;
    private double totalBalance1;
    private double totalBalance2;
    private double totalBalance3;
    private Set<Product> productSet1;
    private Set<Product> productSet2;
    private Set<Product> productSet3;

    private Customer customer1;
    private Customer customer2;
    // endregion test variables

    @Before
    public void setUp() throws Exception {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
        addOrdersToDatabase();
    }

    @After
    public void tearDown() throws Exception {
        orderService.deleteAllOrdersForCustomer(1L);
        orderService.deleteAllOrdersForCustomer(2L);
        customerService.deleteAllCustomers();
        productService.deleteAllProducts();
    }

    @Test
    public void createOrderForCustomer_savesTheOrderInTheDatabase_statusIsCreated() throws Exception {
        Order order4 = Order.builder()
                .customer(customer2)
                .products(new HashSet<>(Collections.singletonList(product7)))
                .orderDate(LocalDate.of(2018, 8, 21))
                .totalBalance(product7.getPrice())
                .build();

        mockMvc.perform(post("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(order4)))
                .andDo(print())
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.customer.firstName", is(order4.getCustomer().getFirstName())))
                .andExpect(jsonPath("$.products[0].productName",
                        is(order4.getProducts().stream().findFirst().get().getProductName())))
                .andExpect(jsonPath("$.totalBalance", is(order4.getTotalBalance())));
    }

    @Test
    public void createOrderForCustomer_returnsOrderIdAutoGeneratedExceptionMessage_whenOrderHasAnIdBeforeBeingSaved() throws Exception {
        Order orderWithForcedId = Order.builder()
                .orderId(4L)
                .customer(customer2)
                .products(new HashSet<>(Collections.singletonList(product7)))
                .orderDate(LocalDate.of(2018, 8, 21))
                .totalBalance(product7.getPrice())
                .build();

        mockMvc.perform(post("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(orderWithForcedId))
                .accept(MediaType.APPLICATION_JSON))
                .andDo(print())
                .andExpect(status().isUnprocessableEntity())
                .andExpect(jsonPath("$.message", is("Order id is auto generated. Please remove this field from your request.")));
    }

    @Test
    public void createOrderForCustomer_returnsValidationMessage_whenNoProductsAreGiven() throws Exception {
        Order order4 = Order.builder()
                .customer(customer2)
                .orderDate(LocalDate.of(2018, 8, 21))
                .totalBalance(product7.getPrice())
                .build();

        mockMvc.perform(post("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(order4)))
                .andDo(print())
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message", is("The field products with value null does not meet requirements. Products is a required field")));
    }

    @Test
    public void createOrderForCustomer_returnsValidationMessage_whenTotalBalanceIsMissing() throws Exception {
        Order order4 = Order.builder()
                .customer(customer2)
                .products(new HashSet<>(Collections.singletonList(product7)))
                .orderDate(LocalDate.of(2018, 8, 21))
                .build();

        mockMvc.perform(post("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(order4)))
                .andDo(print())
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message", is("The field totalBalance with value 0.0 does not meet requirements. Total balance must be at least $1")));
    }

    @Test
    public void createOrderForCustomer_returnsValidationMessage_whenCustomerIsMissing() throws Exception {
        Order order4 = Order.builder()
                .products(new HashSet<>(Collections.singletonList(product7)))
                .orderDate(LocalDate.of(2018, 8, 21))
                .totalBalance(product7.getPrice())
                .build();

        mockMvc.perform(post("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(order4)))
                .andDo(print())
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message", is("The field customer with value null does not meet requirements. Customer is a required field")));
    }

    @Test
    public void getAllOrdersForCustomer_returnsListOfOrders_whenCustomerHasOrders() throws Exception {
        mockMvc.perform(get("/customer/1/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(2)))
                .andExpect(jsonPath("$[0].products", hasSize(3)))
                .andExpect(jsonPath("$[0].customer.lastName", is(customer1.getLastName())))
                .andExpect(jsonPath("$[1].products[0].manufacturer", is(product4.getManufacturer())));
    }

    @Test
    public void getAllOrdersForCustomer_returnsEmptyList_whenCustomerDoesNotExist() throws Exception {
        mockMvc.perform(get("/customer/15/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(0)));
    }

    @Test
    public void getAllOrdersForCustomer_withOptionalDateParam_returnsListOfOrdersForCustomerFilteredByGivenDate_statusIsOK() throws Exception {
        mockMvc.perform(get("/customer/1/order?date=2018-01-03")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(1)))
                .andExpect(jsonPath("$[0].products", hasSize(3)));
    }

    @Test
    public void getAllOrdersForCustomer_withPoorlyFormattedOptionalDateParam_returnsTypeMismatchErrorMessage_statusIsBadRequest() throws Exception {
        mockMvc.perform(get("/customer/1/order?date=01-03-2019")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message", is("Optional Parameter, date, must be a properly formatted date. " +
                        "Example: /customer/1/order?date=2017-02-19")));
    }

    @Test
    public void getAllOrdersForCustomer_withRandomParameter_stillReturnsAllOrdersForCustomer_statusIsOK() throws Exception {
        mockMvc.perform(get("/customer/1/order?cow=2018-03-18")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(2)));
    }

    @Test
    public void updateOrder_updatesTheOrderInTheDatabase_statusIsOk() throws Exception {
        productSet3.add(product7);

        Order updatedOrder = Order.builder()
                .orderId(3L)
                .customer(customer2)
                .products(productSet3)
                .orderDate(LocalDate.of(2019, 1, 17))
                .totalBalance(totalBalance3 + product7.getPrice())
                .build();

        mockMvc.perform(put("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(updatedOrder)))
                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.products", hasSize(3)));
    }

    @Test
    public void updateOrder_returnsValidationErrorMessage_whenOrderDateIsMissing_statusIsBadRequest() throws Exception {
        productSet3.add(product7);

        Order updatedOrder = Order.builder()
                .orderId(3L)
                .customer(customer2)
                .products(productSet3)
                .totalBalance(totalBalance3 + product7.getPrice())
                .build();

        mockMvc.perform(put("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(updatedOrder)))
                .andDo(print())
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message",
                        is("The field orderDate with value null does not meet requirements. Order date is a required field")));
    }

    @Test
    public void updateOrder_returnsOrderNotFoundMessage_whenOrderDoesNotExist_statusIsNotFound() throws Exception {
        productSet3.add(product7);

        Order updatedOrder = Order.builder()
                .orderId(50L)
                .customer(customer2)
                .products(productSet3)
                .orderDate(LocalDate.of(2019, 1, 17))
                .totalBalance(totalBalance3 + product7.getPrice())
                .build();

        mockMvc.perform(put("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(updatedOrder)))
                .andDo(print())
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message",
                        is("Order with id 50 was not found.")));
    }

    @Test
    public void updateOrder_returnsOrderNotFoundErrorMessage_whenOrderIdIsMissing_statusIsNotFound() throws Exception {
        productSet3.add(product7);

        Order updatedOrder = Order.builder()
                .customer(customer2)
                .products(productSet3)
                .orderDate(LocalDate.of(2019, 1, 17))
                .totalBalance(totalBalance3 + product7.getPrice())
                .build();

        mockMvc.perform(put("/order")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .content(mapper.writeValueAsString(updatedOrder)))
                .andDo(print())
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message",
                        is("Order with id null was not found.")));
    }

    @Test
    public void deleteAllOrdersForCustomer_removesAllOrders_statusIsNoContent() throws Exception {
        mockMvc.perform(delete("/customer/2/order"))
                .andExpect(status().isNoContent());
    }

    @Test
    public void deleteOrder_removesSingleOrder_statusIsNoContent() throws Exception {
        mockMvc.perform(delete("/order/3"))
                .andExpect(status().isNoContent());
    }

    @Test
    public void deleteOrder_returnsDataRetrievalFailureErrorMessage_whenOrderIdDoesNotExist_statusIsNotFound() throws Exception {
        mockMvc.perform(delete("/order/16"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message", is("There is no order with id 16 in the database")));
    }

    private void addOrdersToDatabase() {
        customerService.resetAllCustomerIds();
        productService.resetAllProductIds();
        orderService.resetAllOrderIds();

        customer1 = Customer.builder()
                .firstName("Paul")
                .lastName("Ryan")
                .paymentInfo(PaymentInfo.builder()
                        .cardNumber("1234574638")
                        .expirationDate("11/23")
                        .securityCode("873")
                        .zipCode("50892")
                        .build())
                .build();

        customer2 = Customer.builder()
                .firstName("Jim")
                .lastName("Jefferies")
                .paymentInfo(PaymentInfo.builder()
                        .cardNumber("771761728")
                        .expirationDate("12/19")
                        .securityCode("123")
                        .zipCode("63781")
                        .build())
                .build();

        // region products
        product1 = Product.builder()
                .productName("Ipod")
                .description("Music player")
                .manufacturer("Apple")
                .category(Category.ELECTRONICS)
                .price(120.00)
                .build();

        product2 = Product.builder()
                .productName("Merlin")
                .description("Novel about the adventures of King Arthur and a wizard named Merlin.")
                .manufacturer("Penguin Books")
                .category(Category.BOOKS)
                .price(6.99)
                .build();

        product3 = Product.builder()
                .productName("Men's Black Watch")
                .description("A black watch")
                .manufacturer("IZOD")
                .category(Category.CLOTHING_SHOES_JEWELERY_WATCHES)
                .price(45.79)
                .build();

        product4 = Product.builder()
                .productName("Flat Screen TV")
                .description("OLED High Definition TV")
                .manufacturer("Samsung")
                .category(Category.ELECTRONICS)
                .price(599.99)
                .build();

        product5 = Product.builder()
                .productName("Refrigerator")
                .description("Black Refrigerator with water dispenser")
                .manufacturer("Black & Decker")
                .category(Category.HOME_LIVING)
                .price(499.99)
                .build();

        product6 = Product.builder()
                .productName("Summer Dress")
                .description("Yellow sunflower dress for 18-24 mos.")
                .manufacturer("Osh Kosh Ba Gosh")
                .category(Category.CLOTHING_SHOES_JEWELERY_WATCHES)
                .price(21.89)
                .build();

        product7 = Product.builder()
                .productName("Red Dead Redemption 2")
                .description("Cowboy MMO game")
                .manufacturer("Rockstar Games")
                .category(Category.MOVIES_MUSIC_GAMES)
                .price(40.99)
                .build();
        // endregion products

        productSet1 = new HashSet<>(Arrays.asList(product1, product2, product3));
        productSet2 = new HashSet<>(Collections.singletonList(product4));
        productSet3 = new HashSet<>(Arrays.asList(product5, product6));

        totalBalance1 = product1.getPrice() + product2.getPrice() + product3.getPrice();
        totalBalance2 = product4.getPrice();
        totalBalance3 = product5.getPrice() + product6.getPrice();

        order1 = Order.builder()
                .customer(customer1)
                .products(productSet1)
                .orderDate(LocalDate.of(2018, 6, 15))
                .totalBalance(totalBalance1)
                .build();

        order2 = Order.builder()
                .customer(customer1)
                .products(productSet2)
                .orderDate(LocalDate.of(2017, 2, 8))
                .totalBalance(totalBalance2)
                .build();

        order3 = Order.builder()
                .customer(customer2)
                .products(productSet3)
                .orderDate(LocalDate.of(2019, 1, 17))
                .totalBalance(totalBalance3)
                .build();

        customerService.saveCustomer(customer1);
        customerService.saveCustomer(customer2);

        productService.saveProduct(product1);
        productService.saveProduct(product2);
        productService.saveProduct(product3);
        productService.saveProduct(product4);
        productService.saveProduct(product5);
        productService.saveProduct(product6);
        productService.saveProduct(product7);

        orderService.saveOrder(order1);
        orderService.saveOrder(order2);
        orderService.saveOrder(order3);
    }
}
