package com.diamante.orderingsystem.controller;

import lombok.Data;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@Data
@ResponseStatus(value = HttpStatus.UNPROCESSABLE_ENTITY)
public class AutoGeneratedIdException extends RuntimeException {
    private String message;

    public AutoGeneratedIdException(String message) {
        super(message);
        this.message = message;
    }
}